version: '2'
volumes:
  postgres-data:
    driver: local
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  altaria:
    build: .
    command: mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db